# Add your code below
version: "3.1"
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - "27027:27017"
    volumes:
      - task-manager-data:/data/db
    networks:
      - task-manager-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: task-manager-db
    env_file:
    - .env

  app:
    ports:
      - "8000:8000"
    networks:
      - task-manager-network
    container_name: task-manager-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb

volumes:
  task-manager-data:

networks:
  task-manager-network:

