# Add your code below
version: "3.1"
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: hyper-mongo
    env_file: ['.env']

