# Add your code below
version: "3.1"
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: hyper-mongo
    env_file:
    - .env

  hyper-service:
    container_name: hyper-task-manager
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongo-data:

networks:
  hyper-task-manager-network:

